name: Create AVD

on:
  workflow_dispatch:
    inputs:
      api-level:
        type: choice
        required: true
        options: [ 28, 29, 30, 31, 32, 33 ]
      target:
        type: choice
        required: true
        options: [ google_apis, default, playstore ]
      arch:
        type: choice
        required: true
        options: [ arm64-v8a, x86_64, x86 ]

jobs:
  create_avd:
    runs-on: [ self-hosted, macmini-M1 ]
    env:
      MAR_MAR_SMARTLINES_STORE_PASSWORD: '${{ secrets.MAR_MAR_SMARTLINES_STORE_PASSWORD }}'
      MAR_MAR_SMARTLINES_KEY_PASSWORD: '${{ secrets.MAR_MAR_SMARTLINES_KEY_PASSWORD }}'
    steps:
      - name: Create AVD
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ github.event.inputs.api-level }}
          target: ${{ github.event.inputs.target }}
          arch: ${{ github.event.inputs.arch }}
          avd-name: avd-${{ github.event.inputs.api-level }}-${{ github.event.inputs.target }}-${{ github.event.inputs.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          ram-size: 4096M
          script: echo "AVD created"